function parametersTuningUI(parameters, parameterRanges)
    rangeVectors = zeros(1001, length(parameters));
    paramValueDisplays = zeros(length(parameters), 1);

    hMainFigure = figure( ...
        'Name', 'Parameter Tuning', ...
        'MenuBar', 'none', ...
        'Toolbar', 'none', ...
        'HandleVisibility', 'on', ...
        'NumberTitle', 'off', ...
        'IntegerHandle', 'off');
    
    bottom = 350;
    
    for i=1:length(parameters)
        rangeVectors(:, i) = linspace(parameterRanges(i, 1), parameterRanges(i, 2), 1001);
        [~, idx] = min(abs(rangeVectors(:, i) - parameters(i).value));
        initialSliderPosition = idx/1000;

        uicontrol('Parent', hMainFigure, ...
            'Style', 'slider', ...
            'Position', [80, bottom+5-i*100, 400, 23], ...
            'Value', initialSliderPosition, ...
            'Callback', {@slidercb,i});

        uicontrol('Parent', hMainFigure, ...
            'Style', 'text', ...
            'Position', [10, bottom-i*100, 70, 23], ...
            'String', parameters(i).name);

        paramValueDisplays(i) = uicontrol('Parent', hMainFigure, ...
            'Style', 'text', ...
            'Position', [490, bottom+5-i*100, 50, 23], ...
            'BackgroundColor', 'white', ...
            'String', parameters(i).value);
    
    end
    
    function slidercb(slider, ~, ind)        
        val = get(slider, 'Value');
        rangeVectorIndex = round(val*1000)+1;
        parameters(ind).value = rangeVectors(rangeVectorIndex, ind);
        set(paramValueDisplays(ind), 'String', num2str(parameters(ind).value));
    end
end